## Save and Load Trained Model

In [1]:
# Importons les librairies nécessaires
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
# Importons le dataset
data = pd.read_csv('homeprices.csv')
data

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
# Construisons notre modèle
model = linear_model.LinearRegression()
model.fit(data[['area']], data.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [5]:
# Prédisons le prix d'une superficie de 5000 m2
model.predict([[5000]])

array([859554.79452055])

### Save model to file using Python Pickle

In [6]:
import pickle

In [7]:
with open('model_python_pickle', 'wb') as file:
    pickle.dump(model, file)

### Load saved model

In [9]:
with open('model_python_pickle', 'rb') as file:
    pi =pickle.load(file)

In [10]:
# Prédisons le prix d'une superficie de 5000 m2
pi.predict([[5000]])

array([859554.79452055])

### GOOD!

### Save trained model using Joblib

In [11]:
from sklearn.externals import joblib

In [13]:
joblib.dump(model, 'model_python_joblib')

['model_python_joblib']

### Load saved model

In [14]:
jo = joblib.load('model_python_joblib')

In [16]:
# Prédisons le prix d'une superficie de 5000 m2
jo.predict([[5000]])

array([859554.79452055])

## Good! It's work!